version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "80:80"

  api:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: npx json-server -w src/lib/Booking.json --port 3001
    ports:
      - "3001:3001"
